markdown        : redcarpet
name            : Cloud Commander
title           : Cloud Commander
tagLine         : Cloud file manager with console and editor
viewOn          : View Project on
download        : Download
maintainedBy    : This project is maintained by
yandex          : 552807accda3c3ca
ga              : UA-45093573-2
canonical       : cloudcmd.io
repoName        : coderaiser/cloudcmd/edit/dev/HELP.md
improveText     : "Find typo? Help fix it."
repoSource      : coderaiser/cloudcmd
