markdown        : redcarpet
tagLine         : Cloud file manager with console and editor
viewOn          : View Project on
download        : Download
maintainedBy    : This project is maintained by
yandex          : 5c03543d552e9150