name            : Cloud Commander
title           : Cloud Commander
tagLine         : Cloud file manager with console and editor
description     : "Cloud file manager with console and editor. Will help you: create, edit, move and delete files and folders in your favorite browser from any computer."
viewOn          : View Project on GitHub
download        : Download
contact         : Contact
maintainedBy    : This project is maintained by
yandex          : 552807accda3c3ca
metrika         : 24170074
ga              : UA-45093573-2
canonical       : cloudcmd.io
repoName        : coderaiser/cloudcmd/edit/master/HELP.md
improveText     : "Find typo? Help fix it."
repoSource      : coderaiser/cloudcmd
image           : http://cloudcmd.io/img/logo/cloudcmd.png
favicon         : http://cloudcmd.io/favicon.ico
